// Copyright N.A. Tools 2025. All Rights Reserved.

#include "SlickNodes.h"

#include "GraphEditorSettings.h"
#include "SlickNodesConfig.h"
#include "Interfaces/IPluginManager.h"
#include "Styling/SlateStyleMacros.h"
#include "Styling/SlateTypes.h" 
#include "Styling/SlateColor.h"

#include "ISettingsModule.h"
#include "Modules/ModuleManager.h"
#include "Framework/Application/SlateApplication.h" 

#define LOCTEXT_NAMESPACE "FSlickNodesModule" 
#define RootToContentDir Style->RootToContentDir

void FSlickNodesModule::StartupModule() 
{
    if (GIsEditor && !IsRunningCommandlet())
    {
        ApplyEditorStyle();
        SetBaseColors();
    }
    
}

void FSlickNodesModule::ApplyEditorStyle_Static()
{
#if WITH_EDITOR
    if (FSlickNodesModule* Module =
        FModuleManager::GetModulePtr<FSlickNodesModule>("SlickNodes"))
    {
        Module->ApplyEditorStyle();
    }
#endif
}


void FSlickNodesModule::ShutdownModule()
{
    if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
    {
        SettingsModule->UnregisterSettings("Editor", "Plugins", "SlickNodes");
    }
}


void FSlickNodesModule::ApplyEditorStyle()
{
    
    
    const USlickNodesConfig* Settings = GetDefault<USlickNodesConfig>(); 
    FSlateStyleSet* Style = (FSlateStyleSet*)&FAppStyle::Get();
    Style->SetContentRoot(IPluginManager::Get().FindPlugin("SlickNodes")->GetBaseDir() / TEXT("Resources"));
    // Folder Nodes/Regular

    SetStyle(Settings->RegularNodeHeader, Style, "Graph.Node.ColorSpill", "Nodes/Regular/RegularNode_color_spill", true, FVector2D(0,0), FMargin(16.f / 64.f, 12.f / 32.f, 16.f / 64.f, 12.f / 32.f));
    SetStyle(Settings->RegularNodeBody, Style, "Graph.Node.Body", "Nodes/Regular/RegularNode_body", true, FVector2D(0,0), FMargin(16.f / 64.f, 25.f / 64.f, 16.f / 64.f, 16.f / 64.f));
    SetStyle(Settings->RegularNodeBodyGloss, Style, "Graph.Node.TintedBody", "Nodes/Regular/TintedNode_body", true, FVector2D(0,0), FMargin(16.f / 64.f, 25.f / 64.f, 16.f / 64.f, 16.f / 64.f));
    SetStyle(Settings->RegularNodeHeaderGloss, Style, "Graph.Node.TitleGloss", "Nodes/Regular/RegularNode_title_gloss", true, FVector2D(0,0), FMargin(12.0f / 64.0f));
    SetStyle(Settings->RegularNodeTitleHighlight, Style, "Graph.Node.TitleHighlight", "Nodes/Regular/RegularNode_title_highlight", true, FVector2D(0,0), FMargin(16.0f / 64.0f, 1.0f, 16.0f / 64.0f, 0.0f));
    Style->Set("Graph.Node.ShadowSize", FVector2D(12, 12));
    SetStyle(Settings->RegularNodeSelected, Style, "Graph.Node.ShadowSelected", "Nodes/Regular/RegularNode_shadow_selected", true, FVector2D(0,0), FMargin(18.0f / 64.0f));
    SetStyle(Settings->RegularNodeShadow, Style, "Graph.Node.Shadow", "Nodes/Regular/RegularNode_shadow", true, FVector2D(0,0), FMargin(18.0f / 64.0f));
    
    
    // Folder Nodes/Variable
    SetStyle(Settings->VariableNodeBody, Style, "Graph.VarNode.Body", "Nodes/Variable/VarNode_body", true, FVector2D(0,0), FMargin(16.f / 64.f, 12.f / 28.f));
    SetStyle(Settings->VariableNodeHeader, Style, "Graph.VarNode.ColorSpill", "Nodes/Variable/VarNode_color_spill", false, FVector2D(132, 28));
    SetStyle(Settings->VariableNodeGloss, Style, "Graph.VarNode.Gloss", "Nodes/Variable/VarNode_gloss", true, FVector2D(0, 0), FMargin(16.f / 64.f, 16.f / 28.f, 16.f / 64.f, 4.f / 28.f));

    SetStyle(Settings->VariableNodeSelected, Style, "Graph.VarNode.ShadowSelected", "Nodes/Variable/VarNode_shadow_selected", true, FVector2D(0, 0), FMargin(26.0f / 64.0f));
    SetStyle(Settings->VariableNodeShadow, Style, "Graph.VarNode.Shadow", "Nodes/Variable/VarNode_shadow", true, FVector2D(0, 0), FMargin(26.0f / 64.0f));

    SetStyle(Settings->VariableNodeCollapsedBody, Style, "Graph.CollapsedNode.Body", "Nodes/Variable/RegularNode_body", true, FVector2D(0, 0), FMargin(16.f / 64.f, 25.f / 64.f, 16.f / 64.f, 16.f / 64.f));
    SetStyle(Settings->VariableNodeCollapsedHeader, Style, "Graph.CollapsedNode.BodyColorSpill", "Nodes/Variable/CollapsedNode_Body_ColorSpill", true, FVector2D(0, 0), FMargin(64.f / 256.f, 100.f / 256.f, 64.f / 256.f, 64.f / 256.f));
    
    Style->Set("KismetExpression.ReadVariable.Body", new BOX_BRUSH("/Nodes/Variable/Linear_VarNode_Background", FMargin(16.f / 64.f, 12.f / 28.f)));
    Style->Set("KismetExpression.ReadAutogeneratedVariable.Body", new BOX_BRUSH("/Nodes/Variable/Linear_VarNode_Background", FMargin(16.f / 64.f, 12.f / 28.f)));
    
    
    // Folder Nodes/ExecPins
    SetStyle(Settings->RegularExecPinConnected, Style, "Graph.ExecPin.Connected", "Nodes/ExecPins/ExecPin_Connected", false, FVector2D(18.0f, 24.0f));
    SetStyle(Settings->RegularExecPinDisconnected, Style, "Graph.ExecPin.Disconnected", "Nodes/ExecPins/ExecPin_Disconnected", false, FVector2D(18.0f, 24.0f));
    SetStyle(Settings->RegularExecPinConnected, Style, "Graph.ExecPin.ConnectedHovered", "Nodes/ExecPins/ExecPin_Connected", false, FVector2D(18.0f, 24.0f));
    SetStyle(Settings->RegularExecPinDisconnected, Style, "Graph.ExecPin.DisconnectedHovered", "Nodes/ExecPins/ExecPin_Disconnected", false, FVector2D(18.0f, 24.0f));
    
    // Folder Nodes/Pins
    SetStyle(Settings->VariableRoundPinConnected, Style, "Graph.Pin.Connected_VarA", "Nodes/Pins/Pin_connected_VarA", false, FVector2D(15, 11));
    SetStyle(Settings->VariableRoundPinDisconnected, Style, "Graph.Pin.Disconnected_VarA", "Nodes/Pins/Pin_disconnected_VarA", false, FVector2D(15, 11));
    SetStyle(Settings->RegularRoundPinConnected, Style, "Graph.Pin.Connected", "Nodes/Pins/Pin_connected", false, FVector2D(11, 11));
    SetStyle(Settings->RegularRoundPinDisconnected, Style, "Graph.Pin.Disconnected", "Nodes/Pins/Pin_disconnected", false, FVector2D(11, 11));

        // Array Pin
        SetStyle(Settings->ArrayTextureConnected, Style, "Graph.ArrayPin.Connected", "Nodes/Pins/ArrayPin_connected", false, FVector2D(11, 11));
        SetStyle(Settings->ArrayTextureDisconnected, Style, "Graph.ArrayPin.Disconnected", "Nodes/Pins/ArrayPin_disconnected", false, FVector2D(11, 11));
        SetStyle(Settings->ArrayTexture, Style, "Kismet.VariableList.ArrayTypeIcon", "Nodes/Pins/ArrayPin_InVariables", false, FVector2D(16, 16));
        SetStyle(Settings->VariableTexture, Style, "Kismet.VariableList.TypeIcon", "Nodes/Pins/SinglePin_InVariables", false, FVector2D(16, 16));

        // Delegate Pin
        SetStyle(Settings->RegularDelegatePinConnected, Style, "Graph.DelegatePin.Connected", "Nodes/Pins/DelegatePin_Connected", false, FVector2D(11, 11));
        SetStyle(Settings->RegularDelegatePinDisconnected, Style, "Graph.DelegatePin.Disconnected", "Nodes/Pins/DelegatePin_Disconnected", false, FVector2D(11, 11));

        //Hovered over
        SetStyle(Settings->PinHovered, Style, "Graph.Pin.BackgroundHovered", "Nodes/Pins/Pin_hover_cue", true, FVector2D(0, 0), FMargin(1.0f / 32.0f, 1.0f / 8.0f, 1.0f / 32.0f, 1.0f / 8.0f));
    
    // Folder Graph           Background
        Style->Set("Graph.Panel.SolidBackground", new IMAGE_BRUSH("/Graph/GraphPanel_SolidBackground", FVector2D(16, 16), Settings->GridBackgroundColor, ESlateBrushTileType::Both) );
    // Folder Nodes/Pins      Simulation Bubble
    SetStyle(Settings->SimulationBubble, Style, "Graph.ExecutionBubble", "Nodes/Pins/ExecutionBubble", false, FVector2D(32, 32));

    
    // Folder Comment
    
    // Style->Set("Graph.Comment.ColorSpill", new BOX_BRUSH("Comment/Comment_Background", FMargin(16.f / 64.f)));
    //Style->Set("Graph.Comment.Body", new BOX_BRUSH("Comment/Comment_Background", FMargin(16.f / 64.f)));
    //Style->Set("Graph.Comment.Background", new BOX_BRUSH("Comment/Comment_Background", FMargin(16.f / 64.f)));
    //Style->Set("Graph.Node.CommentBubble", new IMAGE_BRUSH("Comment/CommentBubble", FVector2D(32, 32)));
    // Style->Set("Graph.Node.CommentArrow", new IMAGE_BRUSH("Comment/CommentBubbleArrow", FVector2D(11, 11)));
    //Style->Set("Graph.Node.Comment.Background", new IMAGE_BRUSH("Comment/Comment_Background", FVector2D(8.0f, 64.0f)) );
    //Style->Set( "Graph.Node.Comment.Opacity", 1.0f );
    //Graph.Node.Comment.Opacity



    if (FSlateApplication::IsInitialized()){FSlateApplication::Get().GetRenderer()->ReloadTextureResources();}
}





void FSlickNodesModule::SetStyle(const TSoftObjectPtr<UTexture2D> CustomAsset, FSlateStyleSet* Style, const FName& Type,
    const FString& TexturePath, bool bIsBoxBrush, const FVector2D& Size, const FMargin& Margin)
{
    const USlickNodesConfig* Settings = GetDefault<USlickNodesConfig>(); 
    
    if (CustomAsset.LoadSynchronous() && Settings->bOverwriteNodes)
    {
        UTexture2D* LoadedAsset = CustomAsset.LoadSynchronous();
        if (bIsBoxBrush)
        {
            FSlateBoxBrush* CustomBoxBrush = new FSlateBoxBrush(LoadedAsset, Margin);
            Style->Set(Type, CustomBoxBrush);
        }
        else
        {
            FSlateImageBrush* CustomImageBrush = new FSlateImageBrush(LoadedAsset, Size);
            Style->Set(Type, CustomImageBrush);
        }
    }
    else
    {
        if (bIsBoxBrush)
        {
            FSlateBoxBrush* BoxBrush = new BOX_BRUSH(TexturePath, Margin);
            Style->Set(Type, BoxBrush);
        }
        else
        {
            FSlateImageBrush* ImageBrush = new IMAGE_BRUSH(TexturePath, Size);
            Style->Set(Type, ImageBrush);
        }
    }
    
}

void FSlickNodesModule::SetBaseColors()
{
    UGraphEditorSettings* GraphSettings = GetMutableDefault<UGraphEditorSettings>();
    const USlickNodesConfig* Settings = GetDefault<USlickNodesConfig>(); 
    if (GraphSettings && Settings)
    {
        if (Settings->bOverwriteColors)
        {
            
            GraphSettings->EventNodeTitleColor = Settings->EventNodeColor;
            GraphSettings->FunctionCallNodeTitleColor = Settings->FunctionCallNodeColor;
            GraphSettings->PureFunctionCallNodeTitleColor = Settings->PureFunctionNodeColor;
            GraphSettings->ParentFunctionCallNodeTitleColor = Settings->ParentFunctionNodeColor;
            GraphSettings->FunctionTerminatorNodeTitleColor = Settings->FunctionTerminatorColor;
            GraphSettings->ExecBranchNodeTitleColor = Settings->BranchNodeColor;
            GraphSettings->ExecSequenceNodeTitleColor = Settings->SequenceNodeColor;
            GraphSettings->ResultNodeTitleColor = Settings->ResultNodeColor;
            GraphSettings->DefaultCommentNodeTitleColor = Settings->DefaultCommentNodeColor;
            GraphSettings->PreviewNodeTitleColor = Settings->PreviewNodeColor;
                    
            //GraphSettings->SaveConfig();
            
        }
        
    }
}

#undef LOCTEXT_NAMESPACE
IMPLEMENT_MODULE(FSlickNodesModule, SlickNodes)